import type { Product, Trip, Transporter, PickupPoint, Order, User, Review } from "./types";
import { getCountry } from "./countries";

// ─── MOCK USERS ──────────────────────────────────────────────────────────────

export const MOCK_USERS: User[] = [
  {
    id: "u1",
    name: "Parfait Nguembo",
    email: "parfait@example.com",
    phone: "+33612345678",
    role: "vendeur",
    countryCode: "FR",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face",
    createdAt: "2024-01-15",
    isVerified: true,
  },
  {
    id: "u2",
    name: "Christelle Mbaye",
    email: "christelle@example.com",
    phone: "+221771234567",
    role: "vendeur",
    countryCode: "SN",
    avatar: "https://images.unsplash.com/photo-1494790108755-2616b67a8c38?w=100&h=100&fit=crop&crop=face",
    createdAt: "2024-02-10",
    isVerified: true,
  },
  {
    id: "u3",
    name: "Emmanuel Biyong",
    email: "emmanuel@example.com",
    phone: "+237698765432",
    role: "vendeur",
    countryCode: "CM",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face",
    createdAt: "2024-03-05",
    isVerified: true,
  },
  {
    id: "u4",
    name: "Marie-Claire Samba",
    email: "marieclaire@example.com",
    phone: "+236721234567",
    role: "client",
    countryCode: "CF",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face",
    createdAt: "2024-01-20",
    isVerified: true,
  },
  {
    id: "u5",
    name: "Jules Konaté",
    email: "jules@example.com",
    phone: "+22589876543",
    role: "vendeur",
    countryCode: "CI",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face",
    createdAt: "2024-04-01",
    isVerified: false,
  },
];

// ─── MOCK PRODUCTS ────────────────────────────────────────────────────────────

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "p1",
    title: "iPhone 14 Pro 256GB – Neuf sous blister",
    description:
      "iPhone 14 Pro 256 Go couleur or. Neuf, non déverrouillé. Acheté en France. Livraison via GP en 3-4 semaines. Garantie 12 mois. Facture d'achat disponible.",
    price: 850,
    currency: "EUR",
    images: [
      "https://images.unsplash.com/photo-1678685888221-cda773a3dcdb?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600&h=600&fit=crop",
    ],
    category: "electronique",
    originCountry: getCountry("FR")!,
    seller: MOCK_USERS[0],
    stock: 3,
    weight: 0.5,
    dimensions: "15x7x1 cm",
    tags: ["iphone", "apple", "smartphone", "neuf"],
    rating: 4.8,
    reviewCount: 12,
    isAvailable: true,
    createdAt: "2024-05-20",
    colors: ["Or", "Argent", "Noir sidéral", "Violet profond"],
    localDeliveryCostXAF: 2500,
  },
  {
    id: "p2",
    title: "Robe en wax premium – Collection été 2024",
    description:
      "Magnifique robe en tissu wax 100% coton, taille M/L disponible. Couture artisanale sénégalaise de qualité supérieure. Expédition depuis Dakar.",
    price: 45000,
    currency: "XAF",
    images: [
      "https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=600&h=600&fit=crop",
    ],
    category: "mode",
    originCountry: getCountry("SN")!,
    seller: MOCK_USERS[1],
    stock: 10,
    weight: 0.3,
    tags: ["wax", "mode", "robe", "africain"],
    rating: 4.6,
    reviewCount: 28,
    isAvailable: true,
    createdAt: "2024-05-18",
    colors: ["Multicolore kente", "Bleu indigo", "Rouge terre"],
    localDeliveryCostXAF: 2500,
  },
  {
    id: "p3",
    title: "Samsung Galaxy S24 Ultra – 512GB",
    description:
      "Samsung Galaxy S24 Ultra 512 Go, couleur titanium. Neuf avec accessoires. Expédié depuis Douala, Cameroun. Compatible toutes réseaux.",
    price: 720,
    currency: "EUR",
    images: [
      "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=600&h=600&fit=crop",
    ],
    category: "electronique",
    originCountry: getCountry("CM")!,
    seller: MOCK_USERS[2],
    stock: 5,
    weight: 0.6,
    tags: ["samsung", "galaxy", "smartphone", "android"],
    rating: 4.7,
    reviewCount: 9,
    isAvailable: true,
    createdAt: "2024-05-15",
    colors: ["Titanium Noir", "Titanium Gris", "Titanium Violet"],
    localDeliveryCostXAF: 2500,
  },
  {
    id: "p4",
    title: "Huile de palme rouge artisanale – 5L",
    description:
      "Huile de palme rouge pure, extraite artisanalement au Sénégal. Qualité supérieure, sans additifs. Idéale pour la cuisine traditionnelle africaine.",
    price: 18000,
    currency: "XAF",
    images: [
      "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&h=600&fit=crop",
    ],
    category: "alimentation",
    originCountry: getCountry("SN")!,
    seller: MOCK_USERS[1],
    stock: 20,
    weight: 5.2,
    tags: ["huile", "palme", "alimentaire", "artisanal"],
    rating: 4.9,
    reviewCount: 41,
    isAvailable: true,
    createdAt: "2024-05-10",
    localDeliveryCostXAF: 2500,
  },
  {
    id: "p5",
    title: "Ordinateur portable Dell XPS 15 – Intel i7",
    description:
      "Dell XPS 15, processeur Intel Core i7-13700H, 16 Go RAM, SSD 512 Go, écran 4K OLED. État comme neuf, 8 mois d'utilisation. Boîte et chargeur inclus.",
    price: 1100,
    currency: "EUR",
    images: [
      "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&h=600&fit=crop",
    ],
    category: "electronique",
    originCountry: getCountry("FR")!,
    seller: MOCK_USERS[0],
    stock: 1,
    weight: 1.9,
    tags: ["ordinateur", "dell", "laptop", "informatique"],
    rating: 4.5,
    reviewCount: 6,
    isAvailable: true,
    createdAt: "2024-05-08",
    localDeliveryCostXAF: 2500,
  },
  {
    id: "p6",
    title: "Parfum Dior Sauvage – 100ml Authentique",
    description:
      "Parfum Dior Sauvage 100ml authentique, acheté chez Sephora Paris. Flacon complet, non ouvert. Idéal comme cadeau. Livraison GP depuis Paris.",
    price: 95,
    currency: "EUR",
    images: [
      "https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=600&h=600&fit=crop",
    ],
    category: "beaute",
    originCountry: getCountry("FR")!,
    seller: MOCK_USERS[0],
    stock: 4,
    weight: 0.4,
    tags: ["parfum", "dior", "beaute", "cadeau"],
    rating: 4.9,
    reviewCount: 19,
    isAvailable: true,
    createdAt: "2024-05-05",
    localDeliveryCostXAF: 2500,
  },
  {
    id: "p7",
    title: "Boubou grand modèle – Tissu brodé Cameroun",
    description:
      "Boubou grand modèle en tissu bazin riche brodé à la main. Disponible en taille L, XL, XXL. Couleurs : bleu royal, vert émeraude, bordeaux.",
    price: 65000,
    currency: "XAF",
    images: [
      "https://images.unsplash.com/photo-1589571894960-20bbe2828d0a?w=600&h=600&fit=crop",
    ],
    category: "mode",
    originCountry: getCountry("CM")!,
    seller: MOCK_USERS[2],
    stock: 8,
    weight: 0.7,
    tags: ["boubou", "bazin", "mode", "africain", "broderie"],
    rating: 4.7,
    reviewCount: 35,
    isAvailable: true,
    createdAt: "2024-05-01",
    colors: ["Bleu royal", "Vert émeraude", "Bordeaux"],
    localDeliveryCostXAF: 2500,
  },
  {
    id: "p8",
    title: "Casque Sony WH-1000XM5 – Réduction de bruit",
    description:
      "Casque Sony WH-1000XM5 avec réduction de bruit active. Excellente qualité audio, autonomie 30h. Neuf, emballage d'origine. Acheté à Abidjan.",
    price: 280,
    currency: "EUR",
    images: [
      "https://images.unsplash.com/photo-1545127398-14699f92334b?w=600&h=600&fit=crop",
    ],
    category: "electronique",
    originCountry: getCountry("CI")!,
    seller: MOCK_USERS[4],
    stock: 2,
    weight: 0.4,
    tags: ["casque", "sony", "audio", "bluetooth"],
    rating: 4.6,
    reviewCount: 8,
    isAvailable: true,
    createdAt: "2024-04-28",
    colors: ["Noir", "Blanc platine"],
    localDeliveryCostXAF: 2500,
  },
  {
    id: "p9",
    title: "Shea butter pure Sénégal – 500g",
    description:
      "Beurre de karité pur non raffiné, récolté et transformé au Sénégal. Excellente pour la peau et les cheveux. Certifié bio.",
    price: 12000,
    currency: "XAF",
    images: [
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&h=600&fit=crop",
    ],
    category: "beaute",
    originCountry: getCountry("SN")!,
    seller: MOCK_USERS[1],
    stock: 30,
    weight: 0.6,
    tags: ["karité", "shea", "beaute", "naturel", "bio"],
    rating: 4.8,
    reviewCount: 52,
    isAvailable: true,
    createdAt: "2024-04-25",
    localDeliveryCostXAF: 2500,
  },
  {
    id: "p10",
    title: "PS5 PlayStation 5 – Version Disc + 2 manettes",
    description:
      "PlayStation 5 version Disc avec 2 manettes DualSense et 3 jeux inclus (FIFA 24, God of War, Spider-Man 2). Achetée en France, NEUF.",
    price: 550,
    currency: "EUR",
    images: [
      "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=600&h=600&fit=crop",
    ],
    category: "electronique",
    originCountry: getCountry("FR")!,
    seller: MOCK_USERS[0],
    stock: 2,
    weight: 4.5,
    tags: ["ps5", "playstation", "gaming", "console"],
    rating: 4.9,
    reviewCount: 22,
    isAvailable: true,
    createdAt: "2024-04-20",
    localDeliveryCostXAF: 2500,
  },
  {
    id: "p11",
    title: "Huile essentielle de moringa – 100ml Bio",
    description:
      "Huile de graines de moringa pressée à froid, 100% pure et naturelle. Origine Cameroun. Propriétés hydratantes et régénérantes exceptionnelles.",
    price: 8500,
    currency: "XAF",
    images: [
      "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600&h=600&fit=crop",
    ],
    category: "sante",
    originCountry: getCountry("CM")!,
    seller: MOCK_USERS[2],
    stock: 15,
    weight: 0.15,
    tags: ["moringa", "huile", "bio", "naturel", "sante"],
    rating: 4.7,
    reviewCount: 18,
    isAvailable: true,
    createdAt: "2024-04-15",
    localDeliveryCostXAF: 2500,
  },
  {
    id: "p12",
    title: "Machine à coudre Singer 4432 – Professionnelle",
    description:
      "Machine à coudre Singer Heavy Duty 4432, idéale pour les tailleurs. 32 points de couture. Neuve avec accessoires. Achetée à Paris.",
    price: 280,
    currency: "EUR",
    images: [
      "https://images.unsplash.com/photo-1617957772002-57adcf728a62?w=600&h=600&fit=crop",
    ],
    category: "maison",
    originCountry: getCountry("FR")!,
    seller: MOCK_USERS[0],
    stock: 1,
    weight: 6.5,
    tags: ["machine", "couture", "singer", "tailleur"],
    rating: 4.4,
    reviewCount: 7,
    isAvailable: true,
    createdAt: "2024-04-10",
    localDeliveryCostXAF: 2500,
  },

  // ── Mode ──────────────────────────────────────────────────────────────────
  {
    id: "p13",
    title: "Sneakers Nike Air Max 270 – Taille 42",
    description:
      "Nike Air Max 270 coloris blanc/noir, taille 42. Neuves dans leur boîte d'origine, achetées en France. Livraison via GP depuis Paris.",
    price: 130,
    currency: "EUR",
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=600&fit=crop",
    ],
    category: "mode",
    originCountry: getCountry("FR")!,
    seller: MOCK_USERS[0],
    stock: 3,
    weight: 0.9,
    tags: ["nike", "sneakers", "chaussures", "sport"],
    rating: 4.7,
    reviewCount: 14,
    isAvailable: true,
    createdAt: "2024-05-12",
    colors: ["Blanc/Noir", "Gris/Orange", "Noir total"],
    localDeliveryCostXAF: 2500,
  },
  {
    id: "p14",
    title: "Ensemble bogolan homme – Veste + pantalon",
    description:
      "Ensemble complet bogolan (veste + pantalon) teinture naturelle artisanale, motifs traditionnels maliens. Coton épais. Taille L/XL disponible.",
    price: 55000,
    currency: "XAF",
    images: [
      "https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=600&h=600&fit=crop",
    ],
    category: "mode",
    originCountry: getCountry("SN")!,
    seller: MOCK_USERS[1],
    stock: 6,
    weight: 0.8,
    tags: ["bogolan", "africain", "ensemble", "homme"],
    rating: 4.8,
    reviewCount: 22,
    isAvailable: true,
    createdAt: "2024-04-30",
    colors: ["Ocre/Noir", "Naturel/Marron"],
    localDeliveryCostXAF: 2500,
  },
  {
    id: "p15",
    title: "Sac à main cuir véritable – Artisanat marocain",
    description:
      "Sac à main en cuir véritable tanné naturellement, fabriqué à la main par des artisans marocains. Fermeture magnétique, doublure en tissu. 30x20x10 cm.",
    price: 75,
    currency: "EUR",
    images: [
      "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&h=600&fit=crop",
    ],
    category: "mode",
    originCountry: getCountry("MA")!,
    seller: MOCK_USERS[4],
    stock: 8,
    weight: 0.5,
    tags: ["sac", "cuir", "marocain", "artisanat", "femme"],
    rating: 4.6,
    reviewCount: 31,
    isAvailable: true,
    createdAt: "2024-04-22",
    colors: ["Cognac", "Noir", "Bordeaux"],
    localDeliveryCostXAF: 2500,
  },
  {
    id: "p16",
    title: "Pagne Holland – 6 yards authentique",
    description:
      "Pagne Holland 100% coton 6 yards, imprimé wax authentique. Motifs variés disponibles. Tissu de haute qualité utilisé pour confection grand boubou ou robe.",
    price: 28000,
    currency: "XAF",
    images: [
      "https://images.unsplash.com/photo-1590736969955-71cc94901144?w=600&h=600&fit=crop",
    ],
    category: "mode",
    originCountry: getCountry("CI")!,
    seller: MOCK_USERS[4],
    stock: 20,
    weight: 0.4,
    tags: ["pagne", "wax", "holland", "tissu", "couture"],
    rating: 4.9,
    reviewCount: 67,
    isAvailable: true,
    createdAt: "2024-05-02",
    localDeliveryCostXAF: 2500,
  },

  // ── Alimentation ──────────────────────────────────────────────────────────
  {
    id: "p17",
    title: "Café robusta grain entier – 1kg Cameroun",
    description:
      "Café robusta 100% arabica origine Cameroun, torréfié artisanalement. Arômes intenses et fruités. Conditionnement sous vide 1kg.",
    price: 14000,
    currency: "XAF",
    images: [
      "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=600&h=600&fit=crop",
    ],
    category: "alimentation",
    originCountry: getCountry("CM")!,
    seller: MOCK_USERS[2],
    stock: 25,
    weight: 1.1,
    tags: ["café", "robusta", "cameroun", "grain"],
    rating: 4.8,
    reviewCount: 44,
    isAvailable: true,
    createdAt: "2024-05-15",
    localDeliveryCostXAF: 2500,
  },
  {
    id: "p18",
    title: "Piment oiseau séché – 200g",
    description:
      "Piment oiseau séché naturellement, origine Sénégal. Fort en goût, sans additifs. Idéal pour les sauces africaines. Conditionnement hermétique.",
    price: 3500,
    currency: "XAF",
    images: [
      "https://images.unsplash.com/photo-1588252303782-cb80119abd6d?w=600&h=600&fit=crop",
    ],
    category: "alimentation",
    originCountry: getCountry("SN")!,
    seller: MOCK_USERS[1],
    stock: 50,
    weight: 0.25,
    tags: ["piment", "épice", "sénégal", "condiment"],
    rating: 4.7,
    reviewCount: 33,
    isAvailable: true,
    createdAt: "2024-04-18",
    localDeliveryCostXAF: 2500,
  },
  {
    id: "p19",
    title: "Chocolat noir 72% cacao – Tablettes Côte d'Ivoire",
    description:
      "Lot de 6 tablettes chocolat noir 72% pur cacao origine Côte d'Ivoire. Fabrication artisanale. Sans lait, sans OGM. Idéal pour pâtisserie.",
    price: 9500,
    currency: "XAF",
    images: [
      "https://images.unsplash.com/photo-1511381939415-e44015466834?w=600&h=600&fit=crop",
    ],
    category: "alimentation",
    originCountry: getCountry("CI")!,
    seller: MOCK_USERS[4],
    stock: 40,
    weight: 0.6,
    tags: ["chocolat", "cacao", "côte d'ivoire", "artisanal"],
    rating: 4.9,
    reviewCount: 58,
    isAvailable: true,
    createdAt: "2024-05-08",
    localDeliveryCostXAF: 2500,
  },
  {
    id: "p20",
    title: "Thé à la menthe Maroc – Boîte 250g",
    description:
      "Thé vert gunpowder à la menthe fraîche, origine Maroc. Cultivé dans les montagnes du Moyen Atlas. Arômes naturels intenses. Boîte métal 250g.",
    price: 22,
    currency: "EUR",
    images: [
      "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=600&h=600&fit=crop",
    ],
    category: "alimentation",
    originCountry: getCountry("MA")!,
    seller: MOCK_USERS[4],
    stock: 30,
    weight: 0.3,
    tags: ["thé", "menthe", "maroc", "tisane"],
    rating: 4.6,
    reviewCount: 27,
    isAvailable: true,
    createdAt: "2024-04-25",
    localDeliveryCostXAF: 2500,
  },

  // ── Maison ────────────────────────────────────────────────────────────────
  {
    id: "p21",
    title: "Ventilateur de plafond 52\" – Silencieux",
    description:
      "Ventilateur de plafond 52 pouces, 3 vitesses, télécommande incluse. Moteur DC ultra-silencieux. Finition blanc mat. Idéal pour les chaleurs de Bangui.",
    price: 95,
    currency: "EUR",
    images: [
      "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&h=600&fit=crop",
    ],
    category: "maison",
    originCountry: getCountry("BE")!,
    seller: MOCK_USERS[0],
    stock: 5,
    weight: 4.2,
    tags: ["ventilateur", "plafond", "climatisation", "maison"],
    rating: 4.5,
    reviewCount: 11,
    isAvailable: true,
    createdAt: "2024-05-01",
    colors: ["Blanc mat", "Noir"],
    localDeliveryCostXAF: 2500,
  },
  {
    id: "p22",
    title: "Service de vaisselle 18 pièces – Porcelaine",
    description:
      "Service de table 18 pièces en porcelaine blanche (6 assiettes plates, 6 creuses, 6 dessert). Résistant aux chocs et au lave-vaisselle.",
    price: 65,
    currency: "EUR",
    images: [
      "https://images.unsplash.com/photo-1490818387583-1baba5e638af?w=600&h=600&fit=crop",
    ],
    category: "maison",
    originCountry: getCountry("FR")!,
    seller: MOCK_USERS[0],
    stock: 4,
    weight: 5.0,
    tags: ["vaisselle", "porcelaine", "cuisine", "service"],
    rating: 4.4,
    reviewCount: 9,
    isAvailable: true,
    createdAt: "2024-04-12",
    localDeliveryCostXAF: 2500,
  },
  {
    id: "p23",
    title: "Lampe solaire LED – 20W rechargeable",
    description:
      "Lampe LED 20W avec panneau solaire intégré. Autonomie 8h sur pleine charge. Idéale pour les coupures de courant. Résistante à la pluie (IP65).",
    price: 38,
    currency: "EUR",
    images: [
      "https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?w=600&h=600&fit=crop",
    ],
    category: "maison",
    originCountry: getCountry("DE")!,
    seller: MOCK_USERS[2],
    stock: 12,
    weight: 0.8,
    tags: ["lampe", "solaire", "led", "énergie", "éclairage"],
    rating: 4.8,
    reviewCount: 38,
    isAvailable: true,
    createdAt: "2024-05-10",
    localDeliveryCostXAF: 2500,
  },
  {
    id: "p24",
    title: "Climatiseur portable 9000 BTU",
    description:
      "Climatiseur portable 9000 BTU, sans installation, tuyau d'évacuation inclus. Idéal pour une pièce de 20m². Silencieux, télécommande + minuterie.",
    price: 320,
    currency: "EUR",
    images: [
      "https://images.unsplash.com/photo-1615715878771-e0b64b2a2e4e?w=600&h=600&fit=crop",
    ],
    category: "maison",
    originCountry: getCountry("DE")!,
    seller: MOCK_USERS[0],
    stock: 2,
    weight: 28,
    tags: ["climatiseur", "clim", "froid", "maison"],
    rating: 4.3,
    reviewCount: 5,
    isAvailable: true,
    createdAt: "2024-04-05",
    colors: ["Blanc", "Gris"],
    localDeliveryCostXAF: 2500,
  },

  // ── Jouets ────────────────────────────────────────────────────────────────
  {
    id: "p25",
    title: "LEGO City – Set construction 450 pièces",
    description:
      "LEGO City 60271 – Place principale de la ville, 450 pièces. Comprend 8 figurines, véhicules, fontaine et boutiques. Dès 6 ans. Neuf sous blister.",
    price: 55,
    currency: "EUR",
    images: [
      "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=600&h=600&fit=crop",
    ],
    category: "jouets",
    originCountry: getCountry("FR")!,
    seller: MOCK_USERS[0],
    stock: 6,
    weight: 1.2,
    tags: ["lego", "jouet", "construction", "enfant"],
    rating: 4.9,
    reviewCount: 25,
    isAvailable: true,
    createdAt: "2024-05-05",
    localDeliveryCostXAF: 2500,
  },
  {
    id: "p26",
    title: "Poupée Barbie Dreamhouse – Coffret",
    description:
      "Poupée Barbie coffret Dreamhouse avec accessoires (meubles, vêtements, chaussures). Plastique recyclé. Recommandé 3–8 ans. Neuf en boîte.",
    price: 35,
    currency: "EUR",
    images: [
      "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=600&h=600&fit=crop",
    ],
    category: "jouets",
    originCountry: getCountry("FR")!,
    seller: MOCK_USERS[0],
    stock: 8,
    weight: 0.6,
    tags: ["barbie", "poupée", "jouet", "fille"],
    rating: 4.6,
    reviewCount: 18,
    isAvailable: true,
    createdAt: "2024-04-28",
    localDeliveryCostXAF: 2500,
  },
  {
    id: "p27",
    title: "Voiture télécommandée 4x4 – 40 km/h",
    description:
      "Voiture RC 4x4 tout-terrain, vitesse max 40 km/h, télécommande 2.4GHz, portée 100m. Batterie rechargeable USB incluse. Autonomie 30 min.",
    price: 48,
    currency: "EUR",
    images: [
      "https://images.unsplash.com/photo-1558618047-f4e80e3ead16?w=600&h=600&fit=crop",
    ],
    category: "jouets",
    originCountry: getCountry("DE")!,
    seller: MOCK_USERS[2],
    stock: 10,
    weight: 0.8,
    tags: ["voiture", "télécommandée", "rc", "jouet", "garçon"],
    rating: 4.5,
    reviewCount: 21,
    isAvailable: true,
    createdAt: "2024-05-03",
    colors: ["Rouge", "Bleu", "Vert"],
    localDeliveryCostXAF: 2500,
  },
  {
    id: "p28",
    title: "Kit éducatif – Tablette enfant 7\" + stylet",
    description:
      "Tablette Android 7 pouces dédiée enfant, contrôle parental intégré, 32 jeux éducatifs préinstallés. Coque anti-choc. Batterie 4000mAh.",
    price: 79,
    currency: "EUR",
    images: [
      "https://images.unsplash.com/photo-1632765854612-9b02b6ec2b15?w=600&h=600&fit=crop",
    ],
    category: "jouets",
    originCountry: getCountry("BE")!,
    seller: MOCK_USERS[0],
    stock: 4,
    weight: 0.5,
    tags: ["tablette", "enfant", "éducatif", "jouet"],
    rating: 4.7,
    reviewCount: 16,
    isAvailable: true,
    createdAt: "2024-05-07",
    colors: ["Rose", "Bleu ciel", "Jaune"],
    localDeliveryCostXAF: 2500,
  },

  // ── Sport ─────────────────────────────────────────────────────────────────
  {
    id: "p29",
    title: "Ballon de football Nike Strike – Taille 5",
    description:
      "Ballon officiel Nike Strike taille 5, chambre à air butyl, couture machine. Idéal pour le jeu extérieur sur tous terrains. Résistant à l'humidité.",
    price: 28,
    currency: "EUR",
    images: [
      "https://images.unsplash.com/photo-1575361204480-aadea25e6e68?w=600&h=600&fit=crop",
    ],
    category: "sport",
    originCountry: getCountry("FR")!,
    seller: MOCK_USERS[0],
    stock: 15,
    weight: 0.45,
    tags: ["ballon", "football", "nike", "sport"],
    rating: 4.7,
    reviewCount: 43,
    isAvailable: true,
    createdAt: "2024-05-11",
    localDeliveryCostXAF: 2500,
  },
  {
    id: "p30",
    title: "Tapis de yoga antidérapant 6mm – 183x61cm",
    description:
      "Tapis de yoga en TPE recyclé, épaisseur 6mm, surface antidérapante double face. Léger (900g), sangle de transport incluse. Idéal yoga, pilates, fitness.",
    price: 32,
    currency: "EUR",
    images: [
      "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&h=600&fit=crop",
    ],
    category: "sport",
    originCountry: getCountry("DE")!,
    seller: MOCK_USERS[2],
    stock: 12,
    weight: 0.9,
    tags: ["yoga", "tapis", "sport", "fitness"],
    rating: 4.5,
    reviewCount: 19,
    isAvailable: true,
    createdAt: "2024-04-20",
    colors: ["Violet", "Bleu marine", "Noir"],
    localDeliveryCostXAF: 2500,
  },
  {
    id: "p31",
    title: "Vélo d'appartement pliable – Résistance magnétique",
    description:
      "Vélo fitness pliable, résistance magnétique 8 niveaux, compteur LCD (vitesse, distance, calories, temps). Silencieux. Charge max 120kg. Poids 12kg.",
    price: 189,
    currency: "EUR",
    images: [
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&h=600&fit=crop",
    ],
    category: "sport",
    originCountry: getCountry("BE")!,
    seller: MOCK_USERS[0],
    stock: 3,
    weight: 12,
    tags: ["vélo", "fitness", "sport", "pliable"],
    rating: 4.4,
    reviewCount: 8,
    isAvailable: true,
    createdAt: "2024-04-15",
    colors: ["Noir/Rouge", "Noir/Bleu"],
    localDeliveryCostXAF: 2500,
  },
  {
    id: "p32",
    title: "Haltères réglables 2x10kg – Fonte",
    description:
      "Paire d'haltères réglables en fonte, de 2 à 10kg par haltère. Disques amovibles, barre antidérapante. Idéal pour musculation à domicile.",
    price: 45,
    currency: "EUR",
    images: [
      "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&h=600&fit=crop",
    ],
    category: "sport",
    originCountry: getCountry("DE")!,
    seller: MOCK_USERS[2],
    stock: 7,
    weight: 20,
    tags: ["haltères", "musculation", "sport", "fonte"],
    rating: 4.6,
    reviewCount: 12,
    isAvailable: true,
    createdAt: "2024-05-14",
    localDeliveryCostXAF: 2500,
  },

  // ── Santé ─────────────────────────────────────────────────────────────────
  {
    id: "p33",
    title: "Tensiomètre numérique bras – Certifié médical",
    description:
      "Tensiomètre électronique bras, mémoire 60 mesures, affichage grand écran, détection arythmie. Certifié CE médical. Piles incluses.",
    price: 38,
    currency: "EUR",
    images: [
      "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&h=600&fit=crop",
    ],
    category: "sante",
    originCountry: getCountry("DE")!,
    seller: MOCK_USERS[2],
    stock: 9,
    weight: 0.35,
    tags: ["tensiomètre", "santé", "médical", "tension"],
    rating: 4.7,
    reviewCount: 26,
    isAvailable: true,
    createdAt: "2024-05-09",
    localDeliveryCostXAF: 2500,
  },
  {
    id: "p34",
    title: "Multivitamines complètes – 90 comprimés",
    description:
      "Complexe multivitamines 26 nutriments essentiels (Vit A, B, C, D3, E, K2 + minéraux). Sans gluten, sans lactose. 3 mois de cure.",
    price: 25,
    currency: "EUR",
    images: [
      "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=600&h=600&fit=crop",
    ],
    category: "sante",
    originCountry: getCountry("FR")!,
    seller: MOCK_USERS[0],
    stock: 20,
    weight: 0.2,
    tags: ["vitamines", "santé", "complément", "nutrition"],
    rating: 4.6,
    reviewCount: 34,
    isAvailable: true,
    createdAt: "2024-04-18",
    localDeliveryCostXAF: 2500,
  },
  {
    id: "p35",
    title: "Tisane détox – Mélange feuilles de neem 100g",
    description:
      "Tisane 100% naturelle à base de feuilles de neem séchées, propriétés antibactériennes et purifiantes. Certifiée bio, origine Cameroun.",
    price: 5500,
    currency: "XAF",
    images: [
      "https://images.unsplash.com/photo-1455099230208-85f8ef45de21?w=600&h=600&fit=crop",
    ],
    category: "sante",
    originCountry: getCountry("CM")!,
    seller: MOCK_USERS[2],
    stock: 35,
    weight: 0.12,
    tags: ["neem", "tisane", "détox", "naturel", "bio"],
    rating: 4.8,
    reviewCount: 47,
    isAvailable: true,
    createdAt: "2024-05-06",
    localDeliveryCostXAF: 2500,
  },

  // ── Beauté ────────────────────────────────────────────────────────────────
  {
    id: "p36",
    title: "Crème L'Oréal Revitalift – Soin visage 50ml",
    description:
      "Crème anti-rides L'Oréal Revitalift 50ml avec acide hyaluronique et Pro-Rétinol. Hydratation 24h. Pour tous types de peaux. Dermatologiquement testé.",
    price: 18,
    currency: "EUR",
    images: [
      "https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=600&h=600&fit=crop",
    ],
    category: "beaute",
    originCountry: getCountry("FR")!,
    seller: MOCK_USERS[0],
    stock: 18,
    weight: 0.1,
    tags: ["crème", "loréal", "visage", "soin", "anti-rides"],
    rating: 4.5,
    reviewCount: 29,
    isAvailable: true,
    createdAt: "2024-05-13",
    localDeliveryCostXAF: 2500,
  },
  {
    id: "p37",
    title: "Kit coiffure professionnelle – Fer + lisseur",
    description:
      "Kit coiffure pro : fer à friser + lisseur céramique ionique 230°C. Chauffe rapide 60 sec. Câble pivotant 360°. Idéal cheveux afro et métissés.",
    price: 55,
    currency: "EUR",
    images: [
      "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&h=600&fit=crop",
    ],
    category: "beaute",
    originCountry: getCountry("FR")!,
    seller: MOCK_USERS[0],
    stock: 7,
    weight: 0.7,
    tags: ["coiffure", "lisseur", "fer", "cheveux", "beauté"],
    rating: 4.7,
    reviewCount: 23,
    isAvailable: true,
    createdAt: "2024-04-26",
    colors: ["Noir/Or", "Rose/Blanc"],
    localDeliveryCostXAF: 2500,
  },
  {
    id: "p38",
    title: "Huile de coco vierge – 500ml Côte d'Ivoire",
    description:
      "Huile de coco vierge pressée à froid, certifiée bio. Multiusages : soin cheveux, peau, cuisine. Sans odeur artificielle. Pot verre 500ml.",
    price: 7500,
    currency: "XAF",
    images: [
      "https://images.unsplash.com/photo-1526887520775-4b14b8aed897?w=600&h=600&fit=crop",
    ],
    category: "beaute",
    originCountry: getCountry("CI")!,
    seller: MOCK_USERS[4],
    stock: 25,
    weight: 0.6,
    tags: ["coco", "huile", "naturel", "cheveux", "peau"],
    rating: 4.9,
    reviewCount: 61,
    isAvailable: true,
    createdAt: "2024-05-16",
    localDeliveryCostXAF: 2500,
  },

  // ── Auto ──────────────────────────────────────────────────────────────────
  {
    id: "p39",
    title: "Huile moteur Total Quartz 5W-40 – 5L",
    description:
      "Huile moteur synthétique Total Quartz 9000 5W-40, 5 litres. Compatible essence et diesel. Homologuée constructeurs (Renault, Peugeot, Citroën, VW). Neuf.",
    price: 45,
    currency: "EUR",
    images: [
      "https://images.unsplash.com/photo-1632833239869-a37e3a5806d2?w=600&h=600&fit=crop",
    ],
    category: "auto",
    originCountry: getCountry("FR")!,
    seller: MOCK_USERS[0],
    stock: 10,
    weight: 4.5,
    tags: ["huile", "moteur", "total", "auto", "5W40"],
    rating: 4.8,
    reviewCount: 17,
    isAvailable: true,
    createdAt: "2024-05-04",
    localDeliveryCostXAF: 2500,
  },
  {
    id: "p40",
    title: "Dashcam 4K – Avant + arrière + GPS",
    description:
      "Caméra embarquée double objectif 4K avant + 1080P arrière, GPS intégré, détection de mouvement, mode parking. Carte SD 64Go incluse.",
    price: 89,
    currency: "EUR",
    images: [
      "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=600&h=600&fit=crop",
    ],
    category: "auto",
    originCountry: getCountry("DE")!,
    seller: MOCK_USERS[2],
    stock: 5,
    weight: 0.3,
    tags: ["dashcam", "caméra", "voiture", "auto", "gps"],
    rating: 4.5,
    reviewCount: 11,
    isAvailable: true,
    createdAt: "2024-04-22",
    localDeliveryCostXAF: 2500,
  },
  {
    id: "p41",
    title: "Kit entretien voiture – Filtre air + huile + bougies",
    description:
      "Kit entretien complet universel : filtre à air, filtre à huile, 4 bougies NGK, joint de vidange. Compatible Peugeot 206/207/208, Renault Clio/Megane.",
    price: 38,
    currency: "EUR",
    images: [
      "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=600&h=600&fit=crop",
    ],
    category: "auto",
    originCountry: getCountry("FR")!,
    seller: MOCK_USERS[0],
    stock: 8,
    weight: 1.5,
    tags: ["entretien", "filtre", "bougie", "auto", "peugeot"],
    rating: 4.6,
    reviewCount: 14,
    isAvailable: true,
    createdAt: "2024-05-17",
    localDeliveryCostXAF: 2500,
  },

  // ── Autre ─────────────────────────────────────────────────────────────────
  {
    id: "p42",
    title: "Dictionnaire sango-français bilingue",
    description:
      "Dictionnaire sango-français complet, 8000 entrées, avec proverbes et expressions idiomatiques. Format poche, 320 pages. Édition 2023 révisée.",
    price: 18,
    currency: "EUR",
    images: [
      "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=600&h=600&fit=crop",
    ],
    category: "autre",
    originCountry: getCountry("FR")!,
    seller: MOCK_USERS[0],
    stock: 20,
    weight: 0.3,
    tags: ["dictionnaire", "sango", "français", "livre", "langue"],
    rating: 4.9,
    reviewCount: 38,
    isAvailable: true,
    createdAt: "2024-05-18",
    localDeliveryCostXAF: 2500,
  },
  {
    id: "p43",
    title: "Cartable scolaire + fournitures complètes",
    description:
      "Kit rentrée complet : cartable 30L, 5 cahiers, 2 classeurs, trousse avec stylos/crayons/règle/compas. Idéal primaire et collège. Marque Jansport.",
    price: 52,
    currency: "EUR",
    images: [
      "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=600&h=600&fit=crop",
    ],
    category: "autre",
    originCountry: getCountry("BE")!,
    seller: MOCK_USERS[0],
    stock: 15,
    weight: 1.8,
    tags: ["cartable", "scolaire", "fournitures", "école"],
    rating: 4.6,
    reviewCount: 20,
    isAvailable: true,
    createdAt: "2024-04-30",
    colors: ["Bleu marine", "Rouge", "Noir"],
    localDeliveryCostXAF: 2500,
  },
  {
    id: "p44",
    title: "Imprimante jet d'encre HP DeskJet 2720",
    description:
      "Imprimante jet d'encre HP DeskJet 2720, Wi-Fi, impression recto-verso automatique, 5.5 ppm noir. Compatible Windows/Mac/Android. Neuve avec cartouches.",
    price: 65,
    currency: "EUR",
    images: [
      "https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=600&h=600&fit=crop",
    ],
    category: "autre",
    originCountry: getCountry("FR")!,
    seller: MOCK_USERS[0],
    stock: 3,
    weight: 2.5,
    tags: ["imprimante", "hp", "wifi", "bureau", "impression"],
    rating: 4.4,
    reviewCount: 9,
    isAvailable: true,
    createdAt: "2024-05-02",
    localDeliveryCostXAF: 2500,
  },

  // ── Électronique (compléments) ────────────────────────────────────────────
  {
    id: "p45",
    title: "Tablette Samsung Galaxy Tab S9 – 256GB",
    description:
      "Samsung Galaxy Tab S9 256Go Wi-Fi, écran AMOLED 11\", S Pen inclus, RAM 8Go. Neuve sous blister, achetée en Belgique. Garantie 12 mois.",
    price: 650,
    currency: "EUR",
    images: [
      "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600&h=600&fit=crop",
    ],
    category: "electronique",
    originCountry: getCountry("BE")!,
    seller: MOCK_USERS[0],
    stock: 2,
    weight: 0.5,
    tags: ["samsung", "tablette", "android", "s9"],
    rating: 4.8,
    reviewCount: 7,
    isAvailable: true,
    createdAt: "2024-05-19",
    colors: ["Graphite", "Beige"],
    localDeliveryCostXAF: 2500,
  },
  {
    id: "p46",
    title: "Chargeur solaire portable 20000mAh",
    description:
      "Batterie externe 20000mAh avec panneau solaire intégré, 2 ports USB + USB-C. Charge solaire d'appoint ou prise secteur. IP65 waterproof. Idéal voyages.",
    price: 42,
    currency: "EUR",
    images: [
      "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=600&h=600&fit=crop",
    ],
    category: "electronique",
    originCountry: getCountry("DE")!,
    seller: MOCK_USERS[2],
    stock: 14,
    weight: 0.45,
    tags: ["chargeur", "solaire", "batterie", "externe", "powerbank"],
    rating: 4.6,
    reviewCount: 32,
    isAvailable: true,
    createdAt: "2024-05-07",
    colors: ["Noir", "Kaki"],
    localDeliveryCostXAF: 2500,
  },
  {
    id: "p47",
    title: "Montre connectée Apple Watch Series 9",
    description:
      "Apple Watch Series 9 GPS 45mm, boîtier aluminium minuit, bracelet sport. Suivi santé avancé, ECG, GPS, étanche 50m. Neuve avec boîte.",
    price: 380,
    currency: "EUR",
    images: [
      "https://images.unsplash.com/photo-1551816230-ef5deaed4a26?w=600&h=600&fit=crop",
    ],
    category: "electronique",
    originCountry: getCountry("FR")!,
    seller: MOCK_USERS[0],
    stock: 3,
    weight: 0.15,
    tags: ["apple", "watch", "montre", "connectée", "sport"],
    rating: 4.9,
    reviewCount: 15,
    isAvailable: true,
    createdAt: "2024-05-14",
    colors: ["Minuit", "Lumière stellaire", "Rouge"],
    localDeliveryCostXAF: 2500,
  },
];

// ─── MOCK TRANSPORTERS ────────────────────────────────────────────────────────

export const MOCK_TRANSPORTERS: Transporter[] = [
  {
    id: "t1",
    user: {
      id: "tu1",
      name: "Serge Transport",
      email: "serge@transport.com",
      role: "transporteur",
      countryCode: "FR",
      createdAt: "2023-06-01",
      isVerified: true,
    },
    companyName: "Serge Express Paris-Bangui",
    description:
      "Professionnel du transport depuis 8 ans. Spécialiste Paris–Bangui via GP. Colis assurés, suivi en temps réel. Départs bi-mensuels garantis.",
    rating: 4.8,
    reviewCount: 87,
    isVerified: true,
    contact: {
      phone: "+33612345678",
      whatsapp: "+33612345678",
      email: "serge@transport.com",
    },
  },
  {
    id: "t2",
    user: {
      id: "tu2",
      name: "Alpha Logistics",
      email: "alpha@logistics.sn",
      role: "transporteur",
      countryCode: "SN",
      createdAt: "2023-09-15",
      isVerified: true,
    },
    companyName: "Alpha Logistics Dakar",
    description:
      "Transport régulier Dakar–Bangui. Spécialiste en marchandises fragiles et produits alimentaires. Depuis 5 ans sur le corridor.",
    rating: 4.6,
    reviewCount: 54,
    isVerified: true,
    contact: {
      phone: "+221771234567",
      whatsapp: "+221771234567",
    },
  },
  {
    id: "t3",
    user: {
      id: "tu3",
      name: "Douala Transit",
      email: "info@doualatransit.com",
      role: "transporteur",
      countryCode: "CM",
      createdAt: "2024-01-10",
      isVerified: true,
    },
    companyName: "Douala Transit & Fret",
    description:
      "Agence de transit professionnelle. Douala–Bangui en 10–15 jours ouvrables. Dédouanement pris en charge. Route terrestre sécurisée.",
    rating: 4.7,
    reviewCount: 62,
    isVerified: true,
    contact: {
      phone: "+237698765432",
      whatsapp: "+237698765432",
      email: "info@doualatransit.com",
    },
  },
  {
    id: "t4",
    user: {
      id: "tu4",
      name: "Abidjan Cargo",
      email: "info@abidjan-cargo.ci",
      role: "transporteur",
      countryCode: "CI",
      createdAt: "2024-06-01",
      isVerified: true,
    },
    companyName: "Abidjan Cargo Express",
    description:
      "Transport régulier Abidjan–Bangui. Spécialiste marchandises diverses depuis Côte d'Ivoire. Transit rapide en 15–18 jours. Suivi WhatsApp.",
    rating: 4.5,
    reviewCount: 31,
    isVerified: true,
    contact: {
      phone: "+22507123456",
      whatsapp: "+22507123456",
      email: "info@abidjan-cargo.ci",
    },
  },
];

// ─── MOCK TRIPS ───────────────────────────────────────────────────────────────
// Dates futures (référence : avril 2026)

export const MOCK_TRIPS: Trip[] = [
  // ── Serge Express (France → Bangui) ──
  {
    id: "tr1",
    transporter: MOCK_TRANSPORTERS[0],
    originCountry: getCountry("FR")!,
    destinationCity: "Bangui",
    departureDate: "2026-05-05",
    arrivalDate: "2026-05-25",
    pricePerKg: 8,
    currency: "EUR",
    availableCapacity: 150,
    description: "Départ Paris CDG · Vol direct · Colis dédouanés à Bangui M'Poko.",
    isActive: true,
    createdAt: "2026-04-10",
  },
  {
    id: "tr2",
    transporter: MOCK_TRANSPORTERS[0],
    originCountry: getCountry("FR")!,
    destinationCity: "Bangui",
    departureDate: "2026-05-20",
    arrivalDate: "2026-06-10",
    pricePerKg: 8,
    currency: "EUR",
    availableCapacity: 200,
    description: "Départ Paris · Capacité importante · Marchandises lourdes acceptées.",
    isActive: true,
    createdAt: "2026-04-10",
  },
  {
    id: "tr3",
    transporter: MOCK_TRANSPORTERS[0],
    originCountry: getCountry("FR")!,
    destinationCity: "Bangui",
    departureDate: "2026-06-08",
    arrivalDate: "2026-06-28",
    pricePerKg: 7.5,
    currency: "EUR",
    availableCapacity: 180,
    description: "Promo juin · Tarif réduit · Départ Paris Roissy.",
    isActive: true,
    createdAt: "2026-04-10",
  },
  // ── Alpha Logistics (Sénégal → Bangui) ──
  {
    id: "tr4",
    transporter: MOCK_TRANSPORTERS[1],
    originCountry: getCountry("SN")!,
    destinationCity: "Bangui",
    departureDate: "2026-05-08",
    arrivalDate: "2026-05-28",
    pricePerKg: 3500,
    currency: "XAF",
    availableCapacity: 80,
    description: "Départ Dakar · Transit N'Djamena · Colis fragiles acceptés.",
    isActive: true,
    createdAt: "2026-04-10",
  },
  {
    id: "tr5",
    transporter: MOCK_TRANSPORTERS[1],
    originCountry: getCountry("SN")!,
    destinationCity: "Bangui",
    departureDate: "2026-05-22",
    arrivalDate: "2026-06-11",
    pricePerKg: 3200,
    currency: "XAF",
    availableCapacity: 120,
    description: "Départ Dakar · Route directe · Alimentaires et textiles bienvenus.",
    isActive: true,
    createdAt: "2026-04-10",
  },
  // ── Douala Transit (Cameroun → Bangui) ──
  {
    id: "tr6",
    transporter: MOCK_TRANSPORTERS[2],
    originCountry: getCountry("CM")!,
    destinationCity: "Bangui",
    departureDate: "2026-05-10",
    arrivalDate: "2026-05-24",
    pricePerKg: 2500,
    currency: "XAF",
    availableCapacity: 300,
    description: "Départ Douala port · Route terrestre Bertoua → Bangui · 14 jours.",
    isActive: true,
    createdAt: "2026-04-10",
  },
  {
    id: "tr7",
    transporter: MOCK_TRANSPORTERS[2],
    originCountry: getCountry("CM")!,
    destinationCity: "Bangui",
    departureDate: "2026-05-28",
    arrivalDate: "2026-06-11",
    pricePerKg: 2200,
    currency: "XAF",
    availableCapacity: 400,
    description: "Grand convoi mai · Tarif volume · Dédouanement inclus.",
    isActive: true,
    createdAt: "2026-04-10",
  },
  // ── Abidjan Cargo (Côte d'Ivoire → Bangui) ──
  {
    id: "tr8",
    transporter: MOCK_TRANSPORTERS[3],
    originCountry: getCountry("CI")!,
    destinationCity: "Bangui",
    departureDate: "2026-05-12",
    arrivalDate: "2026-05-28",
    pricePerKg: 3000,
    currency: "XAF",
    availableCapacity: 100,
    description: "Départ Abidjan · Transit Yamoussoukro → Bangui · 16 jours.",
    isActive: true,
    createdAt: "2026-04-10",
  },
  {
    id: "tr9",
    transporter: MOCK_TRANSPORTERS[3],
    originCountry: getCountry("CI")!,
    destinationCity: "Bangui",
    departureDate: "2026-06-02",
    arrivalDate: "2026-06-18",
    pricePerKg: 2800,
    currency: "XAF",
    availableCapacity: 150,
    description: "Départ Abidjan · Promo juin · Électronique et mode acceptés.",
    isActive: true,
    createdAt: "2026-04-10",
  },
];

// ─── MOCK PICKUP POINTS ───────────────────────────────────────────────────────

export const MOCK_PICKUP_POINTS: PickupPoint[] = [
  {
    id: "pp1",
    name: "DiasporaMarket – Dépôt Central Bangui",
    address: "Avenue Boganda, en face de l'hôtel Oubangui",
    city: "Bangui",
    phone: "+236721234567",
    openingHours: "Lun–Sam : 8h–18h | Dim : 9h–13h",
    coordinates: { lat: 4.3612, lng: 18.5550 },
    isActive: true,
  },
  {
    id: "pp2",
    name: "Point Retrait – Marché Central",
    address: "Marché Central de Bangui, Quartier Commerce",
    city: "Bangui",
    phone: "+236769876543",
    openingHours: "Lun–Sam : 7h30–17h",
    coordinates: { lat: 4.3647, lng: 18.5589 },
    isActive: true,
  },
  {
    id: "pp3",
    name: "DiasporaMarket – Agence Saïd",
    address: "Boulevard du Général de Gaulle, PK5",
    city: "Bangui",
    phone: "+236758765432",
    openingHours: "Lun–Ven : 8h–17h | Sam : 8h–12h",
    coordinates: { lat: 4.3581, lng: 18.5498 },
    isActive: true,
  },
];

// ─── MOCK ORDERS ──────────────────────────────────────────────────────────────

export const MOCK_ORDERS: Order[] = [
  {
    id: "o1",
    orderNumber: "DM-2024-00142",
    client: MOCK_USERS[3],
    items: [
      { product: MOCK_PRODUCTS[0], quantity: 1, unitPrice: 850 },
    ],
    totalAmount: 850,
    status: "expedie",
    paymentMethod: "orange_money",
    paymentStatus: "bloque",
    escrowReleased: false,
    pickupPoint: MOCK_PICKUP_POINTS[0],
    trackingNumber: "GP-FR-2024-88421",
    transporter: MOCK_TRANSPORTERS[0],
    createdAt: "2024-06-01",
    updatedAt: "2024-06-10",
  },
  {
    id: "o2",
    orderNumber: "DM-2024-00138",
    client: MOCK_USERS[3],
    items: [
      { product: MOCK_PRODUCTS[3], quantity: 2, unitPrice: 18000 },
      { product: MOCK_PRODUCTS[8], quantity: 1, unitPrice: 12000 },
    ],
    totalAmount: 48000,
    status: "pret_retrait",
    paymentMethod: "cash",
    paymentStatus: "bloque",
    escrowReleased: false,
    pickupPoint: MOCK_PICKUP_POINTS[1],
    trackingNumber: "GP-SN-2024-77341",
    transporter: MOCK_TRANSPORTERS[1],
    createdAt: "2024-05-20",
    updatedAt: "2024-06-15",
  },
];

// ─── MOCK REVIEWS ─────────────────────────────────────────────────────────────

export const MOCK_REVIEWS: Review[] = [
  {
    id: "r1",
    author: MOCK_USERS[3],
    rating: 5,
    comment: "Très rapide, colis bien emballé. Je recommande Serge Express !",
    targetId: "t1",
    targetType: "transporter",
    createdAt: "2024-05-15",
  },
  {
    id: "r2",
    author: MOCK_USERS[3],
    rating: 4,
    comment: "Produit conforme à la description. Livraison en 4 semaines.",
    targetId: "p1",
    targetType: "product",
    createdAt: "2024-05-18",
  },
];

// ─── STATS MOCK ───────────────────────────────────────────────────────────────

export const MOCK_STATS = {
  totalProducts: 248,
  totalSellers: 42,
  totalOrders: 1382,
  totalTransporters: 18,
  countriesActive: 8,
  satisfactionRate: 97,
};
